FROM fedora:42 AS build-fedora
ARG NAME=vlc-discordrpc-plugin
ARG VERSION

RUN dnf install -y git gcc-c++ make cmake glibc-static dos2unix libstdc++-static pkgconfig vlc-devel libcurl-devel rpm-build fedora-packager && dnf clean all

WORKDIR /app
COPY . .

RUN dos2unix ./fedora/*.spec

RUN rpmdev-setuptree && \
    git archive --format=tar.gz \
    --prefix=${NAME}/ \
    -o $(rpm --eval '%{_sourcedir}')/${VERSION}.tar.gz HEAD && \
    rpmbuild -ba fedora/vlc-discordrpc-plugin.spec

RUN mkdir -p /outputs/fedora/${VERSION} && \
    cp $(rpm --eval '%{_rpmdir}')/x86_64/${NAME}-${VERSION}*.rpm /outputs/fedora/${VERSION} && \
    cp $(rpm --eval '%{_srcrpmdir}')/${NAME}-${VERSION}*.src.rpm /outputs/fedora/${VERSION}

FROM scratch AS exporter
COPY --from=build-fedora /outputs/fedora .
