#!/bin/sh
set -e

case "$1" in
	configure)
		echo "Configuring vlc-discordrpc-plugin..."
		
		if command -v vlc >/dev/null 2>&1; then
			vlc -I dummy --no-interact --reset-plugins-cache vlc://quit >/dev/null 2>&1 || true
			echo "   \033[0;32m[+]\033[0m VLC plugins cache updated successfully."
		else
			echo "   \033[0;33m[!]\033[0m warning: VLC binary not found. The VLC plugins cache could not be updated."
			exit 1
		fi

		if [ -x /usr/bin/vlcrcedit ]; then
			/usr/bin/vlcrcedit --install
			if [ $? -eq 0 ]; then
				echo "   \033[0;32m[+]\033[0m Plugin configuration installed successfully."
			else
				exit 1
			fi
		else
			echo "   \033[0;31m[!]\033[0m error: vlcrcedit could not be found during installation"
			exit 1
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)

	;;

	*)
		echo "postinst called with unknown argument: \`$1'" >&2
		exit 1
	;;
esac

exit 0