#!/bin/sh
set -e

case "$1" in
	configure)
		echo "Configuring vlc-discordrpc-plugin..."
		
		if command -v vlc >/dev/null 2>&1; then
			vlc -I dummy --no-interact --reset-plugins-cache vlc://quit >/dev/null 2>&1 || true
			echo -e "   \033[0;32m[+]\033[0m VLC plugins cache updated successfully."
		else
			echo -e "   \033[0;33m[!]\033[0m warning: VLC binary not found. Please ensure VLC is installed to use this plugin."
		fi

		if [ -x /usr/bin/vlcrcedit ]; then
			/usr/bin/vlcrcedit --install >/dev/null 2>&1 || true
			echo -e "   \033[0;32m[+]\033[0m VLC vlcrc file edit updated successfully."
		else
			echo -e "   \033[0;33m[!]\033[0m warning: vlcrcedit not found. Please ensure vlcrcedit is installed to update VLC vlcrc file."
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)

	;;

	*)
		echo "postinst called with unknown argument: \`$1'" >&2
		exit 1
	;;
esac

exit 0