#!/bin/sh
set -e

case "$1" in
	configure)
		echo "Configuring vlc-discordrpc-plugin..."
		
		for dir in /usr/lib/*/vlc; do
			if [ -d "$dir" ] && [ -x "$dir/vlc-cache-gen" ]; then
				"$dir/vlc-cache-gen" "$dir/plugins" || true
			fi
		done
		echo "VLC plugins cache updated successfully."
		
		echo "======================================================================="
		echo " Plugin installed! To enable it in your VLC, run the following command"
		echo " as your regular user in the terminal:"
		echo "    vlcrcedit --install"
		echo "======================================================================="
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
	;;

	*)
		echo "postinst called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0