#!/bin/sh
set -e

case "$1" in
	remove|deconfigure)
		if pgrep -x "vlc" > /dev/null; then
			echo "   \033[0;31merror: VLC is running. Please close it before removing the plugin.\033[0m"
			exit 1
		fi
	
		echo "Removing vlc-discordrpc-plugin..."

		if [ -x /usr/bin/vlcrcedit ]; then
			/usr/bin/vlcrcedit --uninstall
			if [ $? -eq 0 ]; then
				echo "   \033[0;32m[-]\033[0m Plugin configuration successfully removed."
			else
				echo "   \033[0;33m[!]\033[0m warning: Failed to remove plugin configuration. Please remove the plugin configuration manually from vlcrc file."
			fi
		else
			echo "   \033[0;33m[!]\033[0m warning: vlcrcedit not found. Please remove the plugin configuration manually from vlcrc file."
		fi
	
		if command -v vlc >/dev/null 2>&1; then
			vlc -I dummy --no-interact --reset-plugins-cache vlc://quit >/dev/null 2>&1 || true
			echo "   \033[0;32m[-]\033[0m VLC plugins cache updated successfully."
		else
			echo "   \033[0;33m[!]\033[0m warning: VLC binary not found. The VLC plugins cache could not be updated."
		fi
	;;

	upgrade|failed-upgrade)
	;;

	*)
		echo "prerm called with unknown argument: \`$1'" >&2
		exit 1
	;;
esac

exit 0