#!/bin/sh
set -e

case "$1" in
	remove|deconfigure)
		if pgrep -x "vlc" > /dev/null; then
			echo "warning: VLC is running. You may need to restart VLC for changes to take effect." >&2
		fi
	
		echo "Removing vlc-discordrpc-plugin..."

		for dir in /usr/lib/*/vlc; do
			if [ -d "$dir" ] && [ -x "$dir/vlc-cache-gen" ]; then
				"$dir/vlc-cache-gen" "$dir/plugins" || true
			fi
		done
		echo "VLC plugins cache updated successfully."
	;;

	upgrade|failed-upgrade)
		exit 0
	;;

	*)
		echo "prerm called with unknown argument: \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0